- name: Create packer path
  file:
    name: "{{ packer_path }}"
    state: directory

- name: Downloading packer
  get_url:
    url: "{{ packer_base_url }}/{{ packer_version }}_{{ ansible_system.lower() }}_{{ packer_arch }}.zip"
    dest: "{{ packer_download_cache }}"
    sha256sum: "{{ packer_sha256sum }}"

- name: Installing packer
  unarchive:
    src: "{{ packer_download_cache }}"
    dest: "{{ packer_path }}"
    mode: 0755
    copy: no

- name: Setting fact
  set_fact:
    packer_installed_version: "{{ packer_version }}"

- name: Cleanup
  file:
    path: "{{ packer_path }}"
    state: absent
